name: Flutter CI for FMT-APP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.5'  # Manually specify a stable Flutter version

    - name: Install dependencies
      run: |
        echo "Running flutter pub get..."
        flutter pub get

    - name: Run unit tests
      run: |
        echo "Running flutter tests..."
        flutter test

    - name: Build APK
      run: |
        echo "Building APK..."
        flutter build apk --release

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: FMT-APP-APK
        path: build/app/outputs/flutter-apk/app-release.apk

