name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: "3.13.9"  # Specify Flutter version explicitly

    - name: Install Flutter dependencies
      run: flutter pub get
      working-directory: ./fot_mail_track  # Update this path to the location of your `pubspec.yaml`

    - name: Run Flutter tests
      run: flutter test
      working-directory: ./fot_mail_track  # Ensure the tests run in the correct directory

    - name: Build APK for Android
      run: flutter build apk --release
      working-directory: ./fot_mail_track  # Ensure build happens in correct directory

    - name: Upload APK Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: ./fot_mail_track/build/app/outputs/flutter-apk/app-release.apk
