name: Flutter CI/CD for FMT-APP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Run unit tests
      run: flutter test

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v2
      with:
        name: FMT-APP-APK
        path: build/app/outputs/flutter-apk/app-release.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Play Credentials
      run: |
        echo $PLAY_STORE_SERVICE_ACCOUNT > $HOME/play-store-credentials.json

    - name: Install Fastlane (for Play Store deployment)
      run: |
        sudo apt-get install ruby ruby-dev build-essential
        sudo gem install fastlane -NV

    - name: Deploy to Google Play
      run: |
        fastlane supply --aab build/app/outputs/flutter-apk/app-release.apk \
        --package_name ${{ secrets.PACKAGE_NAME }} \
        --json_key $HOME/play-store-credentials.json \
        --track production

