name: Flutter CI for FMT-APP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.0'

    - name: Install dependencies
      run: |
        cd fot_mail_track
        flutter pub get

    - name: Run unit tests
      run: |
        cd fot_mail_track
        flutter test

    - name: Build APK
      run: |
        cd fot_mail_track
        flutter build apk --release

    - name: Upload APK as artifact
      run: |
        cd fot_mail_track
        cp build/app/outputs/flutter-apk/app-release.apk ../
      uses: actions/upload-artifact@v3
      with:
        name: FMT-APP-APK
        path: app-release.apk


